name: helpers_plethora
description: An helpful variety of extensions.
version: 2.2.0
repository: https://github.com/Marco87Developer/helpers_plethora
homepage: https://marco87.dev

environment:
  sdk: ^3.1.0

dependencies:
  collection: ^1.18.0
  intl: ^0.18.1
  meta: ^1.10.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
